In [1]:
import torch

In [49]:
# create
a = torch.FloatTensor([[1,2,3],[4,5,6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
a.shape

torch.Size([2, 3])

In [23]:
b = torch.FloatTensor(100)
b

tensor([ 0.0000e+00, -2.0000e+00,  9.2251e-35, -4.6577e-10,  4.2039e-44,
         0.0000e+00,  8.7396e+26,  4.5783e-41,  8.7396e+26,  4.5783e-41,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  7.1466e-44,
         0.0000e+00,  8.7396e+26,  4.5783e-41,  8.7396e+26,  4.5783e-41,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  3.5733e-43,  0.0000e+00,  8.8282e-44,
         0.0000e+00,  8.7397e+26,  4.5783e-41,  8.7

In [12]:
b.shape

torch.Size([100])

In [21]:
x1 = torch.FloatTensor(3,2,4).zero_()
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
x2 = torch.zeros(3,2,4)
x2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
x3 = torch.zeros_like(x1)
x3

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
x = torch.randn((2,3))
x

tensor([[ 1.1778, -1.2132, -0.1041],
        [ 0.3456,  1.2857, -0.6548]])

In [26]:
x.random_(0,10)
x.uniform_(0,1)
x.normal_(mean = 0, std =1)
x.bernoulli_(p=0.5)

tensor([[1., 0., 1.],
        [1., 0., 0.]])

In [28]:
# shape
a.shape

torch.Size([2, 3])

In [29]:
a.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [30]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
a.stride()

(3, 1)

In [34]:
a.T.stride()

(1, 3)

In [37]:
a.is_contiguous(), a.T.is_contiguous()

(True, False)

In [38]:
a.reshape(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [44]:
a.reshape((3,2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [45]:
# casting
a.type_as(torch.IntTensor())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [46]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [47]:
a.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [48]:
a.type_as(torch.ByteTensor())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)

In [50]:
# indexing
a[0,0]

tensor(1.)

In [51]:
a[0:2,1]

tensor([2., 5.])

In [54]:
# operations
b = torch.FloatTensor([[2,3,4],[1,2,3]])

In [55]:
a+b

tensor([[3., 5., 7.],
        [5., 7., 9.]])

In [56]:
a-b

tensor([[-1., -1., -1.],
        [ 3.,  3.,  3.]])

In [57]:
a*b

tensor([[ 2.,  6., 12.],
        [ 4., 10., 18.]])

In [58]:
a/b

tensor([[0.5000, 0.6667, 0.7500],
        [4.0000, 2.5000, 2.0000]])

In [59]:
a.mul(b)

tensor([[ 2.,  6., 12.],
        [ 4., 10., 18.]])

In [60]:
# comparison
a == b

tensor([[False, False, False],
        [False, False, False]])

In [61]:
a != b

tensor([[True, True, True],
        [True, True, True]])

In [62]:
a > b, a < b

(tensor([[False, False, False],
         [ True,  True,  True]]),
 tensor([[ True,  True,  True],
         [False, False, False]]))

In [63]:
# masks
a[a>b]

tensor([4., 5., 6.])

In [66]:
# universal fn
a.sin(), a.abs()

(tensor([[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [65]:
a.exp(), a.log()

(tensor([[  2.7183,   7.3891,  20.0855],
         [ 54.5982, 148.4132, 403.4288]]),
 tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

In [69]:
a.sum(dim=1), a.sum(dim=0)

(tensor([ 6., 15.]), tensor([5., 7., 9.]))

In [70]:
# false axes

a = torch.FloatTensor([[1,2,3],[10,20,30],[100,200,300]])
a[:,None, :].shape

torch.Size([3, 1, 3])

In [73]:
a[None, :, :], a[:,None, :], a[:,:,None]

(tensor([[[  1.,   2.,   3.],
          [ 10.,  20.,  30.],
          [100., 200., 300.]]]),
 tensor([[[  1.,   2.,   3.]],
 
         [[ 10.,  20.,  30.]],
 
         [[100., 200., 300.]]]),
 tensor([[[  1.],
          [  2.],
          [  3.]],
 
         [[ 10.],
          [ 20.],
          [ 30.]],
 
         [[100.],
          [200.],
          [300.]]]))

In [74]:
# example

def vertical_mean(a):
    result = a.mean(dim=0)
    return result

In [75]:
a = torch.FloatTensor([[1,4],[2,7]])

In [76]:
vertical_mean(a)

tensor([1.5000, 5.5000])

In [89]:
# normalize picture

def normalize_picture(a):
    '''
    a : [batch_size, n_channels, W, L]
    '''
    m = a.mean(dim=(2,3))
    
    sigma = a.std(dim=(2,3))
    
    result = (a-m[:,:,None, None])/sigma[:,:,None, None]
    
    
    return result


In [90]:
batch = torch.randint(0,156,(64,3,300,300), dtype=torch.float32)
batch.mean(dim=(2,3)).shape

torch.Size([64, 3])

In [94]:
B = normalize_picture(batch)
B.shape

torch.Size([64, 3, 300, 300])

In [97]:
B.mean(dim=(2,3)), B.std(dim=(2,3))

(tensor([[-4.1729e-08, -8.2906e-08,  3.3908e-10],
         [-7.8795e-08, -4.6539e-08, -6.2731e-08],
         [ 0.0000e+00, -1.4411e-09,  6.3112e-08],
         [ 3.9503e-08, -1.5683e-09, -7.4048e-08],
         [ 2.5431e-09,  1.6361e-08, -5.2728e-08],
         [-5.5737e-08, -2.0769e-08,  7.5637e-08],
         [-5.2049e-08,  3.2637e-08, -4.4674e-08],
         [ 5.5186e-08,  3.8624e-08,  3.8189e-08],
         [-6.4723e-08,  1.3775e-09, -6.9650e-08],
         [ 7.8498e-08, -7.2225e-08, -3.4693e-08],
         [-4.7217e-08,  6.8898e-08,  6.5698e-08],
         [ 1.5386e-08,  2.2888e-08,  6.4617e-08],
         [ 4.4929e-09, -2.9076e-08, -3.1386e-08],
         [-2.8653e-08, -6.4426e-09,  4.5819e-08],
         [ 6.7986e-08, -4.9930e-08,  4.1623e-08],
         [-4.2809e-08,  8.2737e-08, -5.6118e-08],
         [ 3.2722e-08, -8.8162e-09,  2.6957e-08],
         [ 6.8919e-08, -2.9585e-08, -2.7890e-08],
         [ 4.5183e-08,  4.6455e-08, -5.5016e-08],
         [-2.8080e-08, -5.1689e-08,  6.1501e-08],


In [99]:
# conversions

import numpy as np
a = np.random.rand(3,3)

a

array([[0.41604462, 0.49288141, 0.61154983],
       [0.88254043, 0.04298312, 0.97545273],
       [0.91229918, 0.68778296, 0.06539496]])

In [100]:
b = torch.from_numpy(a)
b

tensor([[0.4160, 0.4929, 0.6115],
        [0.8825, 0.0430, 0.9755],
        [0.9123, 0.6878, 0.0654]], dtype=torch.float64)

In [101]:
b -=b 
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [102]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
c = torch.FloatTensor(2,3,4)
c

tensor([[[2.2421e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [105]:
x = c.numpy()
x

array([[[2.2e-44, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00]],

       [[0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00]]], dtype=float32)

In [111]:
# NN example

def forward_pass(X,w):
    logits = X @ w
    result = torch.sigmoid(logits)
    
    return result

In [112]:
X = torch.FloatTensor([[-5,5],[2,3],[1,-1]])
print(X.shape)
w = torch.FloatTensor([[-0.5],[2.5]])
print(w.shape)
result = forward_pass(X,w)
result

torch.Size([3, 2])
torch.Size([2, 1])


tensor([[1.0000],
        [0.9985],
        [0.0474]])

In [115]:
# CUDA
x = torch.FloatTensor(1024,10024).uniform_()
x

tensor([[0.9553, 0.7675, 0.7037,  ..., 0.5526, 0.7239, 0.7189],
        [0.9570, 0.1025, 0.7250,  ..., 0.6028, 0.0574, 0.6489],
        [0.5467, 0.7437, 0.5784,  ..., 0.7419, 0.1806, 0.7443],
        ...,
        [0.1691, 0.6248, 0.2103,  ..., 0.3415, 0.9384, 0.8752],
        [0.1389, 0.9619, 0.6187,  ..., 0.8829, 0.8926, 0.5819],
        [0.4216, 0.0889, 0.5461,  ..., 0.1181, 0.7095, 0.1233]])

In [116]:
x.is_cuda

False

In [119]:
!nvidia-smi
# mcbook & nvidia does not support cuda from 2019
# my mac has amd graphic


zsh:1: command not found: nvidia-smi
